workflow:
    - publish

shared:
    image: node:6

jobs:
    main:
        steps:
            - install: npm install
            - test: npm test

    publish:
        template: screwdriver-cd/semantic-release
        steps:
            - install: npm install semantic-release
            - publish: npm run semantic-release
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
